#!/usr/bin/env python3
"""Build a PowerShell script that sets process env vars for run-local.ps1 (dot-source)."""

from __future__ import annotations

import argparse
import base64
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

SCRIPT_DIR = Path(__file__).resolve().parent

_VALID_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _read_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        raise SystemExit(f"File is empty: {path}")
    return text


def _read_b64(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


@dataclass(frozen=True)
class Secret:
    """Describes one secret: how the user passes it, and how it becomes an env var."""

    env_var: str
    cli_flag: str
    default_filename: str
    label: str
    encode: Callable[[Path], str]

    @property
    def default_path(self) -> Path:
        return SCRIPT_DIR / self.default_filename


SECRETS: tuple[Secret, ...] = (
    Secret(
        env_var="FIREBASE_SERVICE_ACCOUNT_B64",
        cli_flag="--firebase",
        default_filename="firebase_private_key.json",
        label="Firebase JSON",
        encode=_read_b64,
    ),
    Secret(
        env_var="FIREBASE_DATABASE_URL",
        cli_flag="--firebase-db-url",
        default_filename="firebase_db_url.txt",
        label="Firebase database URL",
        encode=_read_text,
    ),
    Secret(
        env_var="GMAIL_OAUTH_CLIENT_B64",
        cli_flag="--gmail-oauth",
        default_filename="gmail_oauth_client.json",
        label="Gmail OAuth JSON",
        encode=_read_b64,
    ),
    Secret(
        env_var="GMAIL_TOKEN_B64",
        cli_flag="--gmail-token",
        default_filename="gmail_token.json",
        label="Gmail token JSON",
        encode=_read_b64,
    ),
    Secret(
        env_var="TWILIO_ACCOUNT_SID",
        cli_flag="--twilio-sid-file",
        default_filename="twilio_account_sid.txt",
        label="Twilio Account SID file",
        encode=_read_text,
    ),
    Secret(
        env_var="TWILIO_AUTH_TOKEN",
        cli_flag="--twilio-token-file",
        default_filename="twilio_auth_token.txt",
        label="Twilio auth token file",
        encode=_read_text,
    ),
    Secret(
        env_var="TWILIO_STATUS_CALLBACK_BASE_URL",
        cli_flag="--twilio-status-callback-base-url-file",
        default_filename="twilio_status_callback_base_url.txt",
        label="Twilio status callback base URL file",
        encode=_read_text,
    ),
    Secret(
        env_var="TOKU_API_TOKEN",
        cli_flag="--toku-api-token-file",
        default_filename="toku_api_token.txt",
        label="Toku API token file",
        encode=_read_text,
    ),
)

DEFAULT_OUTPUT = SCRIPT_DIR / "env.ps1"


def _ps_env_line(key: str, value: str) -> str:
    if not _VALID_KEY_RE.match(key):
        raise ValueError(f"Invalid environment variable name for PowerShell: {key!r}")
    # Single-quoted PowerShell string: escape ' as ''.
    escaped = value.replace("'", "''")
    return f"$env:{key} = '{escaped}'"


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Build env.ps1: $env:KEY assignments for dot-sourcing in run-local.ps1."
    )
    for secret in SECRETS:
        parser.add_argument(
            secret.cli_flag,
            type=Path,
            default=secret.default_path,
            help=f"{secret.label} (default: {secret.default_filename})",
        )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output path (default: {DEFAULT_OUTPUT.name})",
    )
    return parser


def _path_for(args: argparse.Namespace, secret: Secret) -> Path:
    # argparse stores --foo-bar as args.foo_bar.
    attr = secret.cli_flag.lstrip("-").replace("-", "_")
    return getattr(args, attr).resolve()


def main() -> None:
    args = _build_arg_parser().parse_args()

    paths = {secret.env_var: _path_for(args, secret) for secret in SECRETS}
    for secret in SECRETS:
        path = paths[secret.env_var]
        if not path.is_file():
            raise SystemExit(f"{secret.label} not found: {path}")

    lines = [
        "# Generated by secrets/build_env.py - dot-source from python/: . ./secrets/env.ps1",
        "# Do not commit.",
        "",
    ]
    for secret in SECRETS:
        value = secret.encode(paths[secret.env_var])
        lines.append(_ps_env_line(secret.env_var, value))

    out = args.output.resolve()
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
